#!/usr/bin/env python3
"""Regenerate the shipping lunar coefficients from byte-pinned official DE440s."""
import argparse
import hashlib
import json
import math
import re
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REFERENCE_ENV = ROOT / '.context/accuracy-qualification/python-reference'

KERNEL_SHA256 = 'c1c7feeab882263fc493a9d5a5b2ddd71b54826cdf65d8d17a76126b260a49f2'
KERNEL_URL = 'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de440s.bsp'
SHIPPING_SOURCE_SHA256 = '4301ff85cde083cc7ab74b208e684a424f1ae0f1991ae1265c71dc1420282200'
SHIPPING_ARRAY_SHA256 = '2562169b16711fab7f213dc6194e78dc70bd726ec198b0ca00181b5e27bba2d7'
PAYLOAD_SHA256 = 'a1921ec68223515ce97bea46d6db171329ddba8219c349f4c4b0d2ecce81f89c'
LOWER_TDB = 2415019.5
UPPER_TDB = 2499392.5
SHIPPING_LOWER_TDB = 2414986.5
SHIPPING_UPPER_TDB = 2499425.5
AU_KM = 149597870.7
ERFA_LOCK = ROOT / 'Documentation/Migration/integrated-lunar-erfa-source-lock.json'
ERFA_FILES = ['LICENSE', 'src/erfa.h', 'src/erfam.h'] + ['src/' + name + '.c' for name in ['dtdb', 'pmat06', 'pfw06', 'obl06', 'fw2m', 'ir', 'rx', 'rz']]


def digest(data):
    return hashlib.sha256(data).hexdigest()


def build(kernel_path):
    sys.path.insert(0, str(REFERENCE_ENV))
    import jplephem
    import numpy
    from jplephem.spk import SPK
    source = kernel_path.read_bytes()
    if digest(source) != KERNEL_SHA256:
        raise ValueError('official DE440s source identity mismatch')
    if numpy.__version__ != '2.5.3':
        raise ValueError('generation requires pinned NumPy 2.5.3')
    if jplephem.__version__ != '2.24':
        raise ValueError('generation requires pinned jplephem 2.24')
    reference = json.loads((ROOT / 'Documentation/Migration/lunar-ephemeris-candidate-probe.json').read_bytes())
    actual_source = {p.name: digest(p.read_bytes()) for p in sorted(Path(jplephem.__file__).parent.glob('*.py'))}
    if actual_source != reference['jplephem']['sourceSHA256']:
        raise ValueError('jplephem source identity mismatch')
    kernel = SPK.open(str(kernel_path))
    try:
        moon, earth = kernel[3, 301], kernel[3, 399]
        start, interval, lunar = moon.load_array()
        other_start, other_interval, terrestrial = earth.load_array()
        if (moon.frame, earth.frame, moon.data_type, earth.data_type) != (1, 1, 2, 2):
            raise ValueError('lunar source frame or segment type mismatch')
        if start != other_start or interval != other_interval or lunar.shape != terrestrial.shape or lunar.shape[0] != 3:
            raise ValueError('Moon and Earth coefficient grids differ')
        if moon.start_jd > LOWER_TDB or earth.start_jd > LOWER_TDB or moon.end_jd < UPPER_TDB or earth.end_jd < UPPER_TDB:
            raise ValueError('source segments do not cover required guards')
        first = math.floor((LOWER_TDB - start) / interval)
        # Include the upper endpoint record, matching the qualified SPK excerpt.
        last = math.floor((UPPER_TDB - start) / interval) + 1
        folded = (lunar[:, first:last, :] - terrestrial[:, first:last, :]).transpose(1, 0, 2).astype('<f8')
        if not numpy.isfinite(folded).all():
            raise ValueError('nonfinite lunar coefficient')
        count, _, coefficients = folded.shape
        header = struct.pack('<8sQQdddd', b'MOONDEV1', count, coefficients, start + first * interval, interval, LOWER_TDB, UPPER_TDB)
        payload = header + folded.tobytes()
        if digest(payload) != PAYLOAD_SHA256:
            raise ValueError('generated bundle differs from qualified coefficient identity')
        comments = kernel.daf.comments().encode('ascii')
        shipping_first = math.floor((SHIPPING_LOWER_TDB - start) / interval)
        shipping_last = math.floor((SHIPPING_UPPER_TDB - start) / interval) + 1
        shipping_km = (lunar[:, shipping_first:shipping_last, :] - terrestrial[:, shipping_first:shipping_last, :]).transpose(1, 0, 2).astype('<f8')
        shipping_au = (shipping_km / AU_KM).astype('<f8')
        if not numpy.isfinite(shipping_au).all():
            raise ValueError('nonfinite shipping coefficient')
        shipping_count = shipping_au.shape[0]
        lines = [
            '/* Generated by Scripts/ephemeris/generate-lunar-bundle.py; do not edit. */',
            '/* Heirloom Logic derived data from NASA/JPL DE440s; see moon-NOTICE.txt. */',
            '#define MOON_BUNDLE_START_TDB (' + float(start + shipping_first * interval).hex() + ')',
            '#define MOON_BUNDLE_END_TDB (' + float(SHIPPING_UPPER_TDB).hex() + ')',
            '#define MOON_BUNDLE_STEP_DAYS (' + float(interval).hex() + ')',
            '#define MOON_BUNDLE_RECORD_COUNT ' + str(shipping_count),
            '#define MOON_BUNDLE_COEFFICIENT_COUNT ' + str(coefficients),
            'static const double moon_bundle_coefficients[] = {',
        ]
        lines.extend('    ' + ', '.join(float(value).hex() for value in axis) + ',' for record in shipping_au for axis in record)
        lines.append('};')
        compiled = ('\n'.join(lines) + '\n').encode('ascii')
    finally:
        kernel.close()
    lock = json.loads(ERFA_LOCK.read_bytes())
    erfa_files = {}
    for name in ERFA_FILES:
        path = ROOT / 'Documentation/Migration/LunarBundledSources/ERFA-LICENSE' if name == 'LICENSE' else ROOT / 'Sources/CLibAstronomy/EphemerisTime' / Path(name).name
        value = digest(path.read_bytes())
        if value != lock['filesSHA256'][name]:
            raise ValueError('shipping ERFA source identity mismatch: ' + name)
        erfa_files[str(path.relative_to(ROOT))] = value
    wrapper = ROOT / 'Sources/CLibAstronomy/EphemerisTime/ephemeris_time.c'
    header_path = ROOT / 'Sources/CLibAstronomy/include/ephemeris_time.h'
    manifest = {
        'schemaVersion': 1,
        'classification': 'shipping-geometric-lunar-coefficients-derived-by-Heirloom-Logic-from-official-JPL-DE440s',
        'source': {'url': KERNEL_URL, 'sha256': KERNEL_SHA256, 'bytes': len(source), 'solution': 'DE440', 'producer': 'NASA/JPL', 'originalCommentsResource': 'Documentation/Migration/LunarBundledSources/moon-de440-source-comments.txt', 'originalCommentsSHA256': digest(comments)},
        'generation': {'script': 'Scripts/ephemeris/generate-lunar-bundle.py', 'scriptSHA256': digest(Path(__file__).read_bytes()), 'jplephemVersion': jplephem.__version__, 'numpyVersion': numpy.__version__, 'jplephemSourcesSHA256': actual_source, 'operation': 'subtract matching type-2 Chebyshev records for (3,301) minus (3,399); no refit, truncation, or quantization', 'firstSourceRecord': shipping_first, 'exclusiveLastSourceRecord': shipping_last},
        'qualifiedSlice': {'firstSourceRecord': first, 'exclusiveLastSourceRecord': last, 'file': 'moon-de440.bin (regeneration proof only; not shipped)', 'sha256': digest(payload), 'bytes': len(payload), 'magic': 'MOONDEV1', 'headerBytes': 56, 'byteOrder': 'little-endian', 'scalar': 'Float64', 'layout': 'record,axis,ascending Chebyshev degree', 'recordCount': count, 'coefficientCountPerAxis': coefficients, 'coefficientGridStartJulianDateTDB': start + first * interval, 'intervalDaysTDB': interval},
        'resource': {'file': 'Sources/CLibAstronomy/EphemerisData/moon_data.inc', 'sha256': digest(compiled), 'bytes': len(compiled), 'scalar': 'C double; exact hexadecimal floating constants', 'compiledArrayBytes': int(shipping_au.nbytes), 'arrayLittleEndianFloat64SHA256': digest(shipping_au.tobytes()), 'foldedKmLittleEndianFloat64SHA256': digest(shipping_km.tobytes()), 'layout': 'record,axis,ascending Chebyshev degree', 'recordCount': shipping_count, 'coefficientCountPerAxis': coefficients, 'coefficientGridStartJulianDateTDB': start + shipping_first * interval, 'intervalDaysTDB': interval, 'firstSourceRecord': shipping_first, 'exclusiveLastSourceRecord': shipping_last},
        'state': {'target': 301, 'center': 399, 'sourceCenter': 3, 'sourceFrameID': 1, 'frame': 'ICRF/ICRS axes', 'positionUnits': 'AU (149597870.7 km exactly)', 'analyticDerivativeUnits': 'AU/TDB-day; native rate adapter scales public velocity to AU/TT-day', 'corrections': 'geometric; no light-time or aberration'},
        'coverage': {'physicalLowerJulianDateTDB': SHIPPING_LOWER_TDB, 'physicalUpperJulianDateTDB': SHIPPING_UPPER_TDB, 'requiredLowerJulianDateTT': 2415020.5, 'requiredExclusiveUpperJulianDateTT': 2499391.5, 'transitionWidthDaysTT': 32, 'routing': 'use bundle automatically in the required TT interval; C2 blend to existing model across the exterior 32-day margins; retain existing lunar model farther outside; no opt-in or public-domain change'},
        'nativeTimeFrame': {'erfaVersion': lock['version'], 'erfaCommit': lock['commit'], 'sourceBaseURL': lock['baseURL'], 'filesSHA256': erfa_files, 'wrapperSHA256': digest(wrapper.read_bytes()), 'headerSHA256': digest(header_path.read_bytes()), 'time': 'full ERFA eraDtdb periodic geocentric TDB-TT model, evaluated as (2451545,TT-offset); zero topocentric coordinates', 'rate': 'dTDB/dTT = 1 + centered eraDtdb difference over 0.02 TT day divided by 0.02*86400 seconds', 'outputFrame': 'IAU 2006 mean equatorial J2000, eraPmat06(2451545,0) times ICRS vector'},
        'notices': {'derivedDataProducer': 'Heirloom Logic', 'upstreamProducer': 'NASA/JPL; original comments retained as provenance', 'naifRulesURL': 'https://naif.jpl.nasa.gov/naif/rules.html', 'noticeResource': 'Documentation/Migration/LunarBundledSources/moon-NOTICE.txt', 'noticeSHA256': digest(Path(__file__).with_name('moon-NOTICE.txt').read_bytes()), 'erfaLicense': 'Documentation/Migration/LunarBundledSources/ERFA-LICENSE', 'publicationDOI': '10.3847/1538-3881/abd414'},
    }
    return payload, comments, compiled, (json.dumps(manifest, indent=2, sort_keys=True) + '\n').encode()


def integrity(output, metadata_output):
    """Validate committed assets with only the standard library; no network or kernel."""
    manifest = json.loads((metadata_output / 'moon-de440.manifest.json').read_bytes())
    compiled = (output / 'moon_data.inc').read_bytes()
    if digest(compiled) != SHIPPING_SOURCE_SHA256 or manifest['resource']['sha256'] != SHIPPING_SOURCE_SHA256:
        raise ValueError('bundle drift: compiled source identity')
    values = re.findall(r'[-]?0x[0-9a-f]+\.[0-9a-f]+p[+-][0-9]+', compiled.decode('ascii').split('static const double moon_bundle_coefficients[] = {', 1)[1])
    if len(values) != 21111 * 3 * 13:
        raise ValueError('bundle drift: coefficient layout')
    array_bytes = b''.join(struct.pack('<d', float.fromhex(value)) for value in values)
    if digest(array_bytes) != SHIPPING_ARRAY_SHA256 or manifest['resource']['arrayLittleEndianFloat64SHA256'] != SHIPPING_ARRAY_SHA256:
        raise ValueError('bundle drift: compiled coefficient identity')
    if manifest['source']['sha256'] != KERNEL_SHA256 or manifest['source']['url'] != KERNEL_URL or manifest['qualifiedSlice']['sha256'] != PAYLOAD_SHA256:
        raise ValueError('bundle drift: source identity')
    if manifest['state']['positionUnits'] != 'AU (149597870.7 km exactly)' or manifest['state']['analyticDerivativeUnits'] != 'AU/TDB-day; native rate adapter scales public velocity to AU/TT-day' or manifest['state']['frame'] != 'ICRF/ICRS axes':
        raise ValueError('bundle drift: units or reference axes')
    if (manifest['state']['target'], manifest['state']['center'], manifest['state']['sourceCenter'], manifest['state']['sourceFrameID']) != (301, 399, 3, 1):
        raise ValueError('bundle drift: center or frame contract')
    resource = manifest['resource']
    if (resource['recordCount'], resource['coefficientCountPerAxis'], resource['coefficientGridStartJulianDateTDB'], resource['intervalDaysTDB'], resource['compiledArrayBytes']) != (21111, 13, 2414984.5, 4.0, 6586632):
        raise ValueError('bundle drift: metadata layout')
    coverage = manifest['coverage']
    if (coverage['requiredLowerJulianDateTT'], coverage['requiredExclusiveUpperJulianDateTT'], coverage['physicalLowerJulianDateTDB'], coverage['physicalUpperJulianDateTDB'], coverage['transitionWidthDaysTT']) != (2415020.5, 2499391.5, SHIPPING_LOWER_TDB, SHIPPING_UPPER_TDB, 32):
        raise ValueError('bundle drift: domain routing')
    if digest(Path(__file__).read_bytes()) != manifest['generation']['scriptSHA256']:
        raise ValueError('bundle drift: generator source')
    lock = json.loads(ERFA_LOCK.read_bytes())
    for name in ERFA_FILES:
        path = ROOT / 'Documentation/Migration/LunarBundledSources/ERFA-LICENSE' if name == 'LICENSE' else ROOT / 'Sources/CLibAstronomy/EphemerisTime' / Path(name).name
        if digest(path.read_bytes()) != lock['filesSHA256'][name] or manifest['nativeTimeFrame']['filesSHA256'][str(path.relative_to(ROOT))] != lock['filesSHA256'][name]:
            raise ValueError('bundle drift: official ERFA source ' + name)
    for path, expected in [
        (ROOT / 'Sources/CLibAstronomy/EphemerisTime/ephemeris_time.c', manifest['nativeTimeFrame']['wrapperSHA256']),
        (ROOT / 'Sources/CLibAstronomy/include/ephemeris_time.h', manifest['nativeTimeFrame']['headerSHA256']),
        (metadata_output / 'moon-de440-source-comments.txt', manifest['source']['originalCommentsSHA256']),
        (metadata_output / 'moon-NOTICE.txt', manifest['notices']['noticeSHA256']),
    ]:
        if digest(path.read_bytes()) != expected:
            raise ValueError('bundle drift: ' + str(path))
    print('Lunar bundle checkout integrity: source, coefficient layout, units, centers, guards, and retained notices verified.')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('action', nargs='?', choices=['generate', 'check', 'integrity'])
    parser.add_argument('--check', action='store_true', help='checkout-only integrity check; requires neither original kernel nor Python reference packages')
    parser.add_argument('--kernel', type=Path, default=ROOT / '.context/accuracy-qualification/de440s.bsp')
    parser.add_argument('--output', type=Path, help='custom verification output; defaults to production C data directory')
    parser.add_argument('--metadata-output', type=Path, help='custom manifest/notices output; defaults to Documentation/Migration/LunarBundledSources or a supplied --output directory')
    parser.add_argument('--proof-payload', action='store_true', help='emit the original qualified MOONDEV1 binary for verification only')
    args = parser.parse_args()
    output = args.output or ROOT / 'Sources/CLibAstronomy/EphemerisData'
    metadata_output = args.metadata_output or args.output or ROOT / 'Documentation/Migration/LunarBundledSources'
    if args.check or args.action == 'integrity':
        integrity(output, metadata_output)
        return
    if args.action is None:
        parser.error('choose generate, check, or --check')
    payload, comments, compiled, manifest = build(args.kernel)
    products = {output / 'moon_data.inc': compiled, metadata_output / 'moon-de440-source-comments.txt': comments, metadata_output / 'moon-de440.manifest.json': manifest, metadata_output / 'moon-NOTICE.txt': Path(__file__).with_name('moon-NOTICE.txt').read_bytes()}
    if args.proof_payload:
        products[output / 'moon-de440.bin'] = payload
    if args.action == 'check':
        for path, data in products.items():
            if path.read_bytes() != data:
                raise ValueError('bundle drift: ' + str(path))
    else:
        for path, data in products.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    print('Lunar bundle ' + args.action + ': compiled immutable AU coefficients; source and qualified slice identity verified.')


if __name__ == '__main__':
    main()
