// Generated by Scripts/numerics/solar-altitude/bounds.py --write; do not edit.
// Each bound is the exact value derived there, rounded to binary64 away from zero
// when it is not representable, so no constant here is below the bound it stands for.
// The derivations are in <doc:SolarAltitudeNumerics>; bounds.py --check verifies this file.

/// The derived terms of the geometric solar altitude error budget, in degrees unless named otherwise.
enum SolarAltitudeBounds {
    /// TT days from J2000 where the Earth polynomial coverage starts, inclusive.
    static let polynomialStart = -36524.5

    /// TT days from J2000 where the Earth polynomial coverage stops, exclusive.
    static let polynomialStop = 36889.5

    /// Width of one Earth polynomial segment in TT days.
    static let polynomialSegmentDays = 8.0

    /// Observer height above the ellipsoid the budget allows, in meters.
    static let observerHeightMeters = 10000.0

    /// Days the light-time loop can backdate the Earth position, at most.
    static let backdateMaxDays = 0.005926605298166121

    /// Rounding of a civil day count, in days.
    static let civilCalendarDays = 1.350353162621332e-11

    /// Calendar and civil UTC to TT rounding, through the TT sensitivity.
    static let civilToTTDegrees = 6.3727143904084985e-09

    /// Calendar rounding taken as UT, through the UT sensitivity.
    static let civilToUTDegrees = 4.889662109798609e-09

    /// UT to TT rounding when the engine derived TT, through the TT sensitivity.
    static let forwardTTDegrees = 1.0270867444867774e-15

    /// TT to UT inverse when the engine derived UT, through the UT sensitivity.
    static let ttInverseDegrees = 7.415052575146652e-09

    /// Light-time termination.
    static let lightTimeDegrees = 1.1188078236517764e-09

    /// Earth Rotation Angle rounding.
    static let eraDegrees = 1.6359843392832137e-11

    /// Direction change at one Earth polynomial segment boundary.
    static let joinDegrees = 1.2891492287143822e-11
}
