// Generated by Scripts/solar-numerics/derive_altitude.py; do not edit.
// Partial arithmetic bounds are rounded outward. Classification guards are not altitude terms.
enum SolarAltitudeBounds {
    static let polynomialStart = -36524.5
    static let polynomialStop = 36889.5
    static let polynomialSegmentDays = 8.0
    static let observerHeightMeters = 10000.0
    static let inverseToleranceFloorDays = 1e-12
    static let inverseTolerancePerDay = 4.440892098500626e-16
    static let classificationUTLimit = 37000.0
    static let civilCalendarDays = 1.9744372803387487e-11
    static let civilToTTDays = 5.260697793335522e-11
    static let civilToTTDegrees = 1.9049158472862097e-08
    static let civilToUTDegrees = 7.149499510404482e-09
    static let forwardTTDegrees = 9.28402717478751e-15
    static let ttInverseDegrees = 8.9247138241513e-09
    static let lightTimeDegrees = 2.227608200238734e-09
    static let eraDegrees = 3.300004191721738e-11
    static let joinDegrees = 1.2889183140030296e-11
    static let arrivalJumpInverseDegrees = 0.000905255337463104
    static let arrivalJumpForwardDegrees = 2.8251039602318558e-09
    static let lightTimeJumpDegrees = 2.751443345440725e-06
    static let arrivalUncertaintyBaseDays = 9.699832778384278e-11
    static let arrivalUncertaintyDays = 2.5000978192326726e-06
    static let forwardTTDays = 8.215650915396378e-12
    static let classificationGuardDays = 1e-09
    static let classificationInverseGuardDays = 1.0000003283619554e-09
    static let deltaTJumpDays = 2.5e-06
    static let ttImageSlope = 1.0000003283618477
    static let backdateMaxDays = 0.006
    static let utSensitivityDegreesPerDay = 362.10201608471556
    static let ttSensitivityDegreesPerDay = 0.0011300415840927425
    static let modelStepUTs: [Double] = [-36524.5, -29220.5, -21549.5, -14244.5, -5113.5, 1826.5, 18262.5]
    struct Gap {
        let lower: Double
        let upper: Double
        let lowerEnclosure: Double
        let upperEnclosure: Double
    }
    static let positiveGaps: [Gap] = [
        Gap(
            lower: -29220.499754772914, upper: -29220.49975462963, lowerEnclosure: -29220.499754772918,
            upperEnclosure: -29220.49975462963),
        Gap(
            lower: -21549.49971328403, upper: -21549.499713273824, lowerEnclosure: -21549.499713284033,
            upperEnclosure: -21549.499713273824),
        Gap(
            lower: -14244.499611686779, upper: -14244.49961134397, lowerEnclosure: -14244.49961168678,
            upperEnclosure: -14244.49961134397),
        Gap(
            lower: -5113.499364955383, upper: -5113.499364841, lowerEnclosure: -5113.4993649553835,
            upperEnclosure: -5113.499364841),
    ]
}
