#!/usr/bin/env python3
"""Verify the frozen coefficient archive and embed immutable binary64 tables."""
import argparse
import array
import gzip
import hashlib
import json
import math
from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
BODIES = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
START, STOP = -36524.5, 36889.5


def manifest():
    """The body rows of generation.json, in the shipping order."""
    rows = json.loads((HERE/'data/generation.json').read_text())['bodies']
    if [r['body'] for r in rows] != BODIES:
        raise ValueError('Incomplete body manifest')
    return rows


def load_body(row):
    """Verify one body's archive and return (coefficients, valid) as shipped.

    The hashes are checked against generation.json, the grid and sizes are
    validated, and the exclusions from both validity files are applied, so
    the result is exactly what polynomial-data.h embeds.
    """
    name = row['body']
    qualification = json.loads((HERE/'data/shipping-validity.json').read_text())
    integration = json.loads((HERE/'data/integration-validity.json').read_text())
    data = gzip.decompress((HERE/f'data/{name}.bin.gz').read_bytes())
    valid = (HERE/f'data/{name}.valid').read_bytes()
    if hashlib.sha256(data).hexdigest() != row['coefficientSHA256']:
        raise ValueError(f'{name}: coefficient hash mismatch')
    if hashlib.sha256(valid).hexdigest() != row['validitySHA256']:
        raise ValueError(f'{name}: validity hash mismatch')
    degree, width, count = row['degree'], row['width'], row['segments']
    if degree != 12 or width not in (8, 16, 32) or count != math.ceil((STOP-START)/width):
        raise ValueError(f'{name}: unsupported grid')
    if len(valid) != count or not set(valid) <= {0, 1} or len(data) != count*3*(degree+1)*8:
        raise ValueError(f'{name}: incorrect table size')
    coeff = array.array('d', data)
    if sys.byteorder != 'little': coeff.byteswap()
    if not all(map(math.isfinite, coeff)):
        raise ValueError(f'{name}: nonfinite coefficient')
    exclusions = qualification['invalid'][name] + integration['invalid'][name]
    if any(type(i) is not int or not 0 <= i < count for i in exclusions):
        raise ValueError(f'{name}: invalid exclusion index')
    excluded = set(exclusions)
    return coeff, bytes(0 if i in excluded else v for i,v in enumerate(valid))


def render():
    rows = manifest()
    lines = ['/* Generated by Scripts/performance/polynomial/embed.py. Do not edit. */',
             f'#define POLYNOMIAL_START ({START.hex()})', f'#define POLYNOMIAL_STOP ({STOP.hex()})',
             'typedef struct { int degree; double width; const double *coefficients;',
             '    const unsigned char *valid; } polynomial_model_t;']
    total = 0
    for row in rows:
        name = row['body']
        coeff, valid = load_body(row)
        total += len(coeff)*8+len(valid)
        lines.append(f'static const double polynomial_{name}[] = {{')
        lines.extend(','.join(x.hex() for x in coeff[i:i+6])+',' for i in range(0,len(coeff),6))
        lines.extend(['};', f'static const unsigned char polynomial_valid_{name}[] = {{',
                      ','.join(map(str,valid)), '};'])
    if total > 32*1024*1024: raise ValueError('Tables exceed 32 MiB')
    lines.append('static const polynomial_model_t polynomial_models[] = {')
    lines.extend(f'{{{r["degree"]},{r["width"]},polynomial_{r["body"]},polynomial_valid_{r["body"]}}},'
                 for r in rows)
    lines.append('};')
    return '\n'.join(lines)+'\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = ROOT/'Sources/CLibAstronomy/generated/polynomial-data.h'
    content = render()
    if args.check:
        if target.read_text() != content: raise SystemExit('Polynomial tables are stale')
        print('Polynomial tables match the verified archive')
    else:
        target.write_text(content)
