#!/usr/bin/env python3
"""Generate the IAU 2000B nutation table offline from the checksummed ERFA source."""
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'Scripts/orientation-data'
OUTPUT = ROOT / 'Sources/AstronomyKit/Engine/Orientation/Generated/IAU2000BTerms.swift'

INTEGER = r'\s*(-?\d+)\s*,'
COEFFICIENT = r'\s*(-?\d+\.0)\s*'
ROW = re.compile(r'\{' + INTEGER * 5 + ','.join([COEFFICIENT] * 6) + r'\}')


def generate():
    manifest = json.loads((DATA/'manifest.json').read_text())
    for name, record in manifest['files'].items():
        if hashlib.sha256((DATA/name).read_bytes()).hexdigest() != record['sha256']:
            raise ValueError('Nutation source checksum mismatch')
    source = (DATA/'nut00b.c').read_text()
    start = source.index('x[] = {')
    table = source[start:source.index('};', start)]
    rows = ROW.findall(table)
    if len(rows) != 77 or len(rows) != table.count('{') - 1:
        raise ValueError('Expected all 77 IAU 2000B luni-solar terms')
    entries = []
    for row in rows:
        multipliers = ', '.join(row[:5])
        coefficients = ', '.join(f'{int(value[:-2]):_}' for value in row[5:])
        entries.append(f'        Term({multipliers}, {coefficients}),')
    return '''// Generated by Scripts/generate-nutation-table.py; do not edit.
// The IAU 2000B luni-solar series from ERFA 2.0.1 nut00b.c.
// Source URL and SHA-256: Scripts/orientation-data/manifest.json.

extension Engine.Nutation {
    static let terms: [Term] = [
''' + '\n'.join(entries) + '\n    ]\n}\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit('Generated nutation table differs')
    else:
        OUTPUT.write_text(expected)
    print('Verified nutation table' if args.check else 'Generated nutation table')
