#!/usr/bin/env python3
"""Generate the Swift Pluto tables offline from the checksummed C sources."""
import argparse
import base64
import hashlib
import json
from typing import NamedTuple
from pathlib import Path
import re
import struct

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'Scripts/pluto-data/manifest.json'
ENGINE = 'Sources/CLibAstronomy/astronomy.c'
OUTPUT = ROOT / 'Sources/AstronomyKit/Engine/Gravity/Generated'
J2000 = 2451545.0
AU_KM = 149597870.7
LINE = 128
STATE_TABLE = 'PlutoStateTable'

class Table(NamedTuple):
    """A Chebyshev table: its C array, its Swift file and property, and the
    plu060.bsp (center, target) segment it comes from with the sign applied."""
    array: str
    swift_file: str
    property: str
    segment: tuple
    sign: int

    @property
    def prefix(self):
        return self.array.upper()


TABLES = {
    'Sources/CLibAstronomy/EphemerisData/pluto_barycenter.inc':
        Table('pluto_barycenter_bundle', 'PlutoBarycenterCoefficients.swift', 'barycenter', (0, 9), 1),
    'Sources/CLibAstronomy/EphemerisData/pluto_negative_sun.inc':
        Table('pluto_negative_sun_bundle', 'PlutoSunCoefficients.swift', 'barycenterFromSun', (0, 10), -1),
    'Sources/CLibAstronomy/EphemerisData/pluto_center_offset.inc':
        Table('pluto_center_offset_bundle', 'PlutoCenterCoefficients.swift', 'center', (9, 999), 1),
}

HEADER = '''// Generated by Scripts/generate-pluto-tables.py; do not edit.
// {content}.
// Source path and SHA-256: Scripts/pluto-data/manifest.json.
// swift-format-ignore-file
'''


def state_table_block(source):
    """The text of the C engine's PlutoStateTable, from its declaration to its closing brace."""
    match = re.search(r'static const body_state_t ' + STATE_TABLE + r'\[\] =\n\{.*?\n\};', source, re.S)
    if not match:
        raise ValueError(f'{ENGINE} has no {STATE_TABLE}')
    return match.group(0)


def read_sources(manifest):
    if set(manifest['files']) != set(TABLES):
        raise ValueError('Pluto manifest must list exactly the three Pluto coefficient tables')
    sources = {}
    for name, record in manifest['files'].items():
        data = (ROOT/name).read_bytes()
        if hashlib.sha256(data).hexdigest() != record['sha256']:
            raise ValueError(f'Pluto source checksum mismatch: {name}')
        sources[name] = data.decode('ascii')
    record = manifest['stateTable']
    if record['path'] != ENGINE:
        raise ValueError(f'The Pluto state table must come from {ENGINE}')
    block = state_table_block((ROOT/ENGINE).read_text())
    if hashlib.sha256(block.encode('ascii')).hexdigest() != record['sha256']:
        raise ValueError(f'Pluto state table checksum mismatch: {STATE_TABLE} in {ENGINE}')
    sources[STATE_TABLE] = block
    return sources


def chebyshev_table(source, prefix, array):
    """The table's first TDB in days from J2000, its record length in days, its shape and its coefficients."""
    def define(name, pattern):
        return re.search(r'#define ' + prefix + '_' + name + r' ' + pattern, source).group(1)

    hexadecimal = r'(0x[0-9a-fp.+-]+)'
    start = float.fromhex(define('START_TDB', hexadecimal)) - J2000
    end = float.fromhex(define('END_TDB', hexadecimal)) - J2000
    step = float.fromhex(define('STEP_DAYS', hexadecimal))
    records = int(define('RECORD_COUNT', r'(\d+)'))
    count = int(define('COEFFICIENT_COUNT', r'(\d+)'))
    body = source.split(f'static const double {array}_coefficients[] = {{', 1)[1].split('};', 1)[0]
    items = [item.strip() for item in body.split(',') if item.strip()]
    values = [float.fromhex(item) for item in items]
    if len(values) != records * 3 * count:
        raise ValueError(f'{prefix} holds {len(values)} coefficients, not {records} x 3 x {count}')
    if not start + records * step >= end > start:
        raise ValueError(f'{prefix} does not reach its stated end')
    return start, step, records, count, values


def packed(values):
    """Base64 of the little-endian IEEE 754 bit patterns, as Swift multi-line string lines."""
    text = base64.b64encode(struct.pack(f'<{len(values)}d', *values)).decode('ascii')
    return '\n'.join(text[i:i + LINE] for i in range(0, len(text), LINE))


def table_swift(source, name, content):
    table = TABLES[name]
    start, step, records, count, values = chebyshev_table(source, table.prefix, table.array)
    return HEADER.format(content=content) + f'''
extension Engine.PlutoEphemeris {{
    /// Record by record, then x, y and z, then by ascending degree; AU, ICRS axes.
    static let {table.property} = Engine.ChebyshevTable(
        start: {start!r},
        recordDays: {step!r},
        recordCount: {records:_},
        degreeCount: {count},
        coefficients: Engine.unpackDoubles(
            count: {len(values):_},
            """
{packed(values)}
"""
        )
    )
}}
'''


def state_rows(block):
    """Each state as TT, position and velocity, as the C source spells the numbers."""
    number = r'\s*(-?\d+\.\d+(?:e[-+]?\d+)?)\s*'
    vector = r'\{' + number + ',' + number + ',' + number + r'\}'
    rows = re.findall(r'\{' + number + r',\s*' + vector + r',\s*' + vector + r'\s*\}', block)
    if len(rows) != 51 or block.count('{') != 1 + 3 * len(rows):
        raise ValueError(f'Expected all 51 states of {STATE_TABLE}')
    return rows


def state_swift(block, content):
    rows = state_rows(block)
    lines = '\n'.join(
        f'        TableState(tt: {tt}, position: SIMD3({x}, {y}, {z}), velocity: SIMD3({vx}, {vy}, {vz})),'
        for tt, x, y, z, vx, vy, vz in rows)
    return HEADER.format(content=content) + f'''
extension Engine.Pluto {{
    /// The {len(rows)} tabulated states in time order: TT in days from J2000,
    /// heliocentric position in AU and velocity in AU per day on EQJ axes.
    static let stateTable: [TableState] = [
{lines}
    ]
}}
'''


def generate(manifest, sources):
    files = {}
    for name, record in manifest['files'].items():
        files[TABLES[name].swift_file] = table_swift(sources[name], name, record['content'])
    files['PlutoStateTable.swift'] = state_swift(sources[STATE_TABLE], manifest['stateTable']['content'])
    return files


def spk_records(data):
    """Each (center, target) of a little-endian DAF/SPK file with its type 2 records, in time order.

    A pair split across segments, as PLU060 splits Pluto's center at 2013, has
    its segments joined when each starts where the one before ends.
    """
    if data[:8] != b'DAF/SPK ' or data[88:96] != b'LTL-IEEE':
        raise ValueError('Not a little-endian DAF/SPK file')
    nd, ni = struct.unpack('<ii', data[8:16])
    if (nd, ni) != (2, 6):
        raise ValueError('Unexpected SPK summary format')
    size = nd + (ni + 1) // 2
    segments, record = {}, struct.unpack('<i', data[76:80])[0]
    while record:
        base = (record - 1) * 1024
        following, _, count = struct.unpack('<3d', data[base:base + 24])
        for index in range(int(count)):
            offset = base + 24 + index * size * 8
            target, center, frame, kind, first, last = struct.unpack('<6i', data[offset + 16:offset + 40])
            if (frame, kind) != (1, 2):
                raise ValueError('Expected type 2 segments on J2000 (ICRF) axes')
            epoch, length, words, records = struct.unpack('<4d', data[(last - 4) * 8:last * 8])
            values = struct.unpack(f'<{int(words * records)}d', data[(first - 1) * 8:(first - 1 + int(words * records)) * 8])
            segments.setdefault((center, target), []).append((epoch / 86400, length / 86400, int(words), int(records), values))
        record = int(following)
    joined = {}
    for pair, parts in segments.items():
        parts.sort()
        epoch, length, words, records, values = parts[0]
        values = list(values)
        for part in parts[1:]:
            if part[1:3] != (length, words) or part[0] != epoch + records * length:
                raise ValueError(f'The segments of {pair} do not join')
            records += part[3]
            values.extend(part[4])
        joined[pair] = (epoch, length, words, records, values)
    return joined


def check_published(directory, manifest, sources):
    """Every coefficient against plu060.bsp, and the state table against Astronomy Engine's source."""
    published = manifest['published']['files']
    for name, record in published.items():
        if hashlib.sha256((directory/name).read_bytes()).hexdigest() != record['sha256']:
            raise ValueError(f'Published file checksum mismatch: {name}')
    segments = spk_records((directory/'plu060.bsp').read_bytes())
    compared = 0
    for name, table in TABLES.items():
        epoch, length, size, count, words = segments[table.segment]
        start, step, records, degrees, values = chebyshev_table(sources[name], table.prefix, table.array)
        offset = (start - epoch) / length
        first = int(offset)
        if step != length or size != 2 + 3 * degrees or offset != first or first + records > count:
            raise ValueError(f'{table.prefix} does not fall on the plu060.bsp records of {table.segment}')
        for k in range(records):
            base = (first + k) * size + 2
            for index in range(3 * degrees):
                expected = table.sign * words[base + index] / AU_KM
                if struct.pack('<d', values[k * 3 * degrees + index]) != struct.pack('<d', expected):
                    raise ValueError(f'{table.prefix} record {k}, coefficient {index} differs from plu060.bsp')
        compared += records * 3 * degrees
    upstream = state_table_block((directory/'astronomy.c').read_text())
    if upstream != sources[STATE_TABLE]:
        raise ValueError(f'{STATE_TABLE} differs from Astronomy Engine')
    return compared


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--published', type=Path, metavar='DIR',
                        help='also compare the tables with plu060.bsp and astronomy.c in DIR (see the manifest)')
    args = parser.parse_args()
    manifest = json.loads(MANIFEST.read_text())
    sources = read_sources(manifest)
    if args.published:
        compared = check_published(args.published, manifest, sources)
        print(f'All {compared:,} Pluto coefficients equal plu060.bsp, and {STATE_TABLE} equals Astronomy Engine')
    expected = generate(manifest, sources)
    if args.check:
        present = {path.name for path in OUTPUT.glob('*.swift')}
        if present != set(expected) or any((OUTPUT/name).read_text() != text for name, text in expected.items()):
            raise SystemExit('Generated Pluto tables differ')
    else:
        OUTPUT.mkdir(parents=True, exist_ok=True)
        for path in OUTPUT.glob('*.swift'):
            if path.name not in expected:
                path.unlink()
        for name, text in expected.items():
            (OUTPUT/name).write_text(text)
    print('Verified Pluto tables' if args.check else 'Generated Pluto tables')
