#!/usr/bin/env python3
"""Generate the IAU 2000B nutation table and the equation of the equinoxes complementary terms offline from the checksummed ERFA sources."""
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'Scripts/orientation-data'
GENERATED = ROOT / 'Sources/AstronomyKit/Engine/Orientation/Generated'
OUTPUT = GENERATED / 'IAU2000BTerms.swift'
COMPLEMENTARY_OUTPUT = GENERATED / 'EquinoxComplementaryTerms.swift'

INTEGER = r'\s*(-?\d+)\s*,'
COEFFICIENT = r'\s*(-?\d+\.0)\s*'
ROW = re.compile(r'\{' + INTEGER * 5 + ','.join([COEFFICIENT] * 6) + r'\}')
SERIES_NUMBER = r'\s*(-?\d+\.\d+e-6)\s*'
COMPLEMENTARY_ROW = re.compile(r'\{\{' + r'\s*(-?\d+)\s*,' * 7 + r'\s*(-?\d+)\s*\},' + SERIES_NUMBER + ',' + SERIES_NUMBER + r'\}')


def verify_sources():
    manifest = json.loads((DATA/'manifest.json').read_text())
    for name, record in manifest['files'].items():
        if hashlib.sha256((DATA/name).read_bytes()).hexdigest() != record['sha256']:
            raise ValueError(f'Orientation source checksum mismatch: {name}')


def generate():
    source = (DATA/'nut00b.c').read_text()
    start = source.index('x[] = {')
    table = source[start:source.index('};', start)]
    rows = ROW.findall(table)
    if len(rows) != 77 or len(rows) != table.count('{') - 1:
        raise ValueError('Expected all 77 IAU 2000B luni-solar terms')
    entries = []
    for row in rows:
        multipliers = ', '.join(row[:5])
        coefficients = ', '.join(f'{int(value[:-2]):_}' for value in row[5:])
        entries.append(f'        Term({multipliers}, {coefficients}),')
    return '''// Generated by Scripts/generate-nutation-table.py; do not edit.
// The IAU 2000B luni-solar series from ERFA 2.0.1 nut00b.c.
// Source URL and SHA-256: Scripts/orientation-data/manifest.json.

extension Engine.Nutation {
    static let terms: [Term] = [
''' + '\n'.join(entries) + '\n    ]\n}\n'


def complementary_series(source, name, count):
    start = source.index(f'{name}[] = {{')
    table = source[start:source.index('};', start)]
    rows = COMPLEMENTARY_ROW.findall(table)
    if len(rows) != count or len(rows) != table.count('{{'):
        raise ValueError(f'Expected {count} terms in {name}')
    # swift-format drops the trailing comma from a one-element literal.
    comma = ',' if count > 1 else ''
    return [f'        ComplementaryTerm({", ".join(row[:8])}, {row[8]}, {row[9]}){comma}' for row in rows]


def generate_complementary():
    source = (DATA/'eect00.c').read_text()
    constant = complementary_series(source, 'e0', 33)
    linear = complementary_series(source, 'e1', 1)
    return '''// Generated by Scripts/generate-nutation-table.py; do not edit.
// The complementary terms of the equation of the equinoxes, 33 terms and one
// with a factor of t, from ERFA 2.0.1 eect00.c (IERS Conventions 2003, Table 5.2e).
// Source URL and SHA-256: Scripts/orientation-data/manifest.json.

extension Engine.Nutation {
    static let complementaryConstantTerms: [ComplementaryTerm] = [
''' + '\n'.join(constant) + '''
    ]

    static let complementaryLinearTerms: [ComplementaryTerm] = [
''' + '\n'.join(linear) + '\n    ]\n}\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    verify_sources()
    outputs = {OUTPUT: generate(), COMPLEMENTARY_OUTPUT: generate_complementary()}
    for path, expected in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != expected:
                raise SystemExit(f'Generated table differs: {path.name}')
        else:
            path.write_text(expected)
    print('Verified nutation tables' if args.check else 'Generated nutation tables')
