#!/usr/bin/env python3
"""Embed the qualified Pluto/Sun shared-node binaries and generate direct-source fixtures."""

import argparse
import base64
import hashlib
import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT/'Scripts/pluto-data/de441-evidence.json'
BODIES = {9: 'pluto', 10: 'sun'}
SPEC = importlib.util.spec_from_file_location('moon_generator', ROOT/'Scripts/generate-moon-de441.py')
common = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(common)


def output(name):
    return ROOT/f'Sources/AstronomyKit/Engine/Gravity/Generated/DE441/PlutoDE441{name.title()}Data.swift'


def render(data, name, start, days, count):
    encoded = base64.b64encode(data).decode('ascii')
    payload = '\n'.join(encoded[i:i+128] for i in range(0, len(encoded), 128))
    return f'''// Generated by Scripts/generate-pluto-de441.py; do not edit.
// Qualified source and SHA-256: Scripts/pluto-data/de441-evidence.json.
// swift-format-ignore-file

extension Engine.PlutoDE441 {{
    static let {name} = Table(
        start: {start!r}, days: {days!r}, recordCount: {count},
        data: Engine.unpackBytes(
            count: {len(data)},
            """
{payload}
"""
        )
    )
}}
'''


def reference_fixtures(cache):
    spec = importlib.util.spec_from_file_location('pluto_assessment', ROOT/'Scripts/assess-pluto-de441.py')
    p = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(p)
    evidence = json.loads(MANIFEST.read_bytes())
    reader = p.shared.CachedReader(cache, evidence['source']['retrievedByteRangesSHA256'])
    bodies, rows = {}, []
    for target in BODIES:
        layout = [(p.direct.Segment(**part['segment']), p.direct.RecordMetadata(**part['metadata']), part['firstRecord'], part['recordCount']) for part in evidence['source']['segments'][str(target)]]
        records = p.load_records(reader, layout)
        bodies[target] = records
        chosen = {i*(len(records)-1)//256 for i in range(257)}
        for candidate in evidence['candidates'].values():
            chosen.update(candidate['bodies'][str(target)]['worstRecordIndices'])
        for sample in evidence['fixedSamples']:
            index = int((p.direct.J2000 + sample['tdbDaysFromJ2000'] - records[0][0])/records[0][1])
            chosen.update(i for i in (index-1, index, index+1) if 0 <= i < len(records))
        for index in sorted(chosen):
            start, days, axes = records[index]
            for x in (-1., -.5, 0., .5, 1.):
                position, velocity = p.evaluate(axes, x, days)
                rows.append({'target': target, 'record': index, 'x': x, 'positionKm': position, 'velocityKmPerTDBDay': velocity})
    heliocentric = []
    for sample in evidence['fixedSamples']:
        epoch = sample['tdbDaysFromJ2000']
        position, velocity = p.heliocentric(bodies, p.direct.J2000 + epoch)
        heliocentric.append({'tdb': epoch, 'positionKm': position, 'velocityKmPerTDBDay': velocity})
    result = {'sourceEvidenceSHA256': hashlib.sha256(MANIFEST.read_bytes()).hexdigest(), 'selection': 'For each body: 257 uniform records, all four candidates worst-bound records, records at each of the 72 frozen epochs and their neighbors; each at x=-1,-0.5,0,0.5,1. Heliocentric states at all 72 frozen epochs.', 'bodyRows': rows, 'heliocentricRows': heliocentric}
    path = ROOT/'Scripts/pluto-data/de441-native-fixtures.json'
    path.write_text(json.dumps(result, indent=2, sort_keys=True)+'\n')
    print(f'Wrote {len(rows)} body states and {len(heliocentric)} heliocentric states')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--binaries', type=Path, default=ROOT/'.context/issue-190/candidates')
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--reference-fixtures', action='store_true')
    parser.add_argument('--cache', type=Path, default=ROOT/'.context/issue-184/compact/ranges')
    args = parser.parse_args()
    if args.reference_fixtures:
        reference_fixtures(args.cache)
        return
    evidence = json.loads(MANIFEST.read_bytes())
    if not evidence['assessment']['barycenterRepresentationFullRangeScanned']:
        raise ValueError('candidate has not been scanned over the full accepted range')
    candidate = evidence['candidates']['cubic-float64']
    for target, name in BODIES.items():
        body = candidate['bodies'][str(target)]
        path = output(name)
        data = common.extract(path.read_text()) if args.check else (args.binaries/f'cubic-float64-{target}.bin').read_bytes()
        common.validate(data, body)
        if len(data) != (body['recordCount']+1)*48:
            raise ValueError('shared-node layout differs')
        source = render(data, name, body['startJDTDB']-2451545, body['recordDays'], body['recordCount'])
        if args.check:
            if path.read_text() != source:
                raise SystemExit('Generated DE441 Pluto table differs')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(source)
    print('Verified DE441 Pluto tables' if args.check else 'Wrote DE441 Pluto tables')


if __name__ == '__main__':
    main()
