#!/usr/bin/env python3
"""Generate the IAU 2006/2000A nutation tables and the equation of the equinoxes complementary terms offline from the checksummed ERFA sources."""
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'Scripts/orientation-data'
GENERATED = ROOT / 'Sources/AstronomyKit/Engine/Orientation/Generated'
OUTPUT = GENERATED / 'IAU2000ATerms.swift'
COMPLEMENTARY_OUTPUT = GENERATED / 'EquinoxComplementaryTerms.swift'

INTEGER = r'\s*(-?\d+)\s*,'
COEFFICIENT = r'\s*(-?\d+\.0)\s*'
LUNI_SOLAR_ROW = re.compile(r'\{' + INTEGER * 5 + ','.join([COEFFICIENT] * 6) + r'\}')
PLANETARY_ROW = re.compile(r'\{' + INTEGER * 16 + r'\s*(-?\d+)\s*\}')
SERIES_NUMBER = r'\s*(-?\d+\.\d+e-6)\s*'
COMPLEMENTARY_ROW = re.compile(r'\{\{' + r'\s*(-?\d+)\s*,' * 7 + r'\s*(-?\d+)\s*\},' + SERIES_NUMBER + ',' + SERIES_NUMBER + r'\}')
ADJUSTMENT = re.compile(
    r'fj2 = (-\d+\.\d+e-6) \* t;.*'
    r'\*dpsi = dp \+ dp \* \((\d+\.\d+e-6) \+ fj2\);\s*'
    r'\*deps = de \+ de \* fj2;',
    re.S,
)


def verify_sources():
    manifest = json.loads((DATA/'manifest.json').read_text())
    for name, record in manifest['files'].items():
        if hashlib.sha256((DATA/name).read_bytes()).hexdigest() != record['sha256']:
            raise ValueError(f'Orientation source checksum mismatch: {name}')


def series(source, name, row, count, opening='{', extra=1):
    """The rows of the C table `name`, checking that `row` matched every one of its `count` entries."""
    start = source.index(f'{name}[] = {{')
    table = source[start:source.index('};', start)]
    rows = row.findall(table)
    if len(rows) != count or len(rows) != table.count(opening) - extra:
        raise ValueError(f'Expected all {count} terms in {name}')
    return rows


def generate():
    source = (DATA/'nut00a.c').read_text()
    luni_solar = []
    for row in series(source, 'xls', LUNI_SOLAR_ROW, 678):
        multipliers = ', '.join(row[:5])
        coefficients = ', '.join(f'{int(value[:-2]):_}' for value in row[5:])
        luni_solar.append(f'        LuniSolarTerm({multipliers}, {coefficients}),')
    planetary = []
    for row in series(source, 'xpl', PLANETARY_ROW, 687):
        multipliers = ', '.join(row[:13])
        coefficients = ', '.join(f'{int(value):_}' for value in row[13:])
        planetary.append(f'        PlanetaryTerm({multipliers}, {coefficients}),')
    adjustment = ADJUSTMENT.search((DATA/'nut06a.c').read_text())
    if not adjustment:
        raise ValueError('Expected the IAU 2006 adjustment in nut06a.c')
    j2_rate, longitude_factor = adjustment.groups()
    return f'''// Generated by Scripts/generate-nutation-table.py; do not edit.
// The IAU 2000A luni-solar and planetary series from ERFA 2.0.1 nut00a.c, and
// the IAU 2006 adjustment factors from nut06a.c.
// Source URL and SHA-256: Scripts/orientation-data/manifest.json.

extension Engine.Nutation {{
    /// `iauNut06a` multiplies Δψ by 1 + {longitude_factor} + j2Rate·t and Δε by
    /// 1 + j2Rate·t, with t in Julian centuries.
    static let longitudeFactor = {longitude_factor}
    static let j2Rate = {j2_rate}

    static let luniSolarTerms: [LuniSolarTerm] = [
''' + '\n'.join(luni_solar) + '''
    ]

    static let planetaryTerms: [PlanetaryTerm] = [
''' + '\n'.join(planetary) + '\n    ]\n}\n'


def complementary_series(source, name, count):
    rows = series(source, name, COMPLEMENTARY_ROW, count, opening='{{', extra=0)
    # swift-format drops the trailing comma from a one-element literal.
    comma = ',' if count > 1 else ''
    return [f'        ComplementaryTerm({", ".join(row[:8])}, {row[8]}, {row[9]}){comma}' for row in rows]


def generate_complementary():
    source = (DATA/'eect00.c').read_text()
    constant = complementary_series(source, 'e0', 33)
    linear = complementary_series(source, 'e1', 1)
    return '''// Generated by Scripts/generate-nutation-table.py; do not edit.
// The complementary terms of the equation of the equinoxes, 33 terms and one
// with a factor of t, from ERFA 2.0.1 eect00.c (IERS Conventions 2003, Table 5.2e).
// Source URL and SHA-256: Scripts/orientation-data/manifest.json.

extension Engine.Nutation {
    static let complementaryConstantTerms: [ComplementaryTerm] = [
''' + '\n'.join(constant) + '''
    ]

    static let complementaryLinearTerms: [ComplementaryTerm] = [
''' + '\n'.join(linear) + '\n    ]\n}\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    verify_sources()
    outputs = {OUTPUT: generate(), COMPLEMENTARY_OUTPUT: generate_complementary()}
    for path, expected in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != expected:
                raise SystemExit(f'Generated table differs: {path.name}')
        else:
            path.write_text(expected)
    print('Verified nutation tables' if args.check else 'Generated nutation tables')
