#!/usr/bin/env python3
"""Embed the qualified shared-endpoint DE441 binary, or verify its embedded digest offline."""

import argparse
import base64
import hashlib
import importlib.util
import json
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "Scripts/moon-data/de441-compact-evidence.json"
OUTPUT = ROOT / "Sources/AstronomyKit/Engine/Moon/Generated/DE441/MoonDE441Data.swift"


def validate(data, candidate):
    if len(data) != candidate["encodedBytes"]:
        raise ValueError("DE441 binary length differs from the qualified candidate")
    if hashlib.sha256(data).hexdigest() != candidate["sha256"]:
        raise ValueError("DE441 binary digest differs from the qualified candidate")


def render(data, start, count):
    encoded = base64.b64encode(data).decode("ascii")
    payload = "\n".join(encoded[index:index + 128] for index in range(0, len(encoded), 128))
    return f'''// Generated by Scripts/generate-moon-de441.py; do not edit.
// Source, layout and qualified SHA-256: Scripts/moon-data/de441-compact-evidence.json.
// swift-format-ignore-file

extension Engine.MoonDE441 {{
    static let start = {start!r}
    static let recordCount = {count}
    static let data = Engine.unpackBytes(
        count: {len(data)},
        """
{payload}
"""
    )
}}
'''


def extract(source):
    return base64.b64decode(source.split('"""', 2)[1], validate=False)


def reference_fixtures(cache):
    spec = importlib.util.spec_from_file_location("qualification", ROOT / "Scripts/qualify-moon-de441.py")
    q = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(q)
    evidence = json.loads(MANIFEST.read_bytes())
    reader = q.CachedReader(cache / "ranges", evidence["source"]["retrievedByteRangesSHA256"])
    count = evidence["coverage"]["recordCount"]
    start = evidence["coverage"]["segments"][0]["firstRecordStartJulianDateTDB"]
    chosen = {index * (count - 1) // 256 for index in range(257)}
    for candidate in evidence["candidates"]:
        for key, value in candidate.items():
            if key.endswith("AtRecordStartJD"):
                chosen.add(round((value - start) / 4))
    for row in evidence["coverage"]["specialBoundaryRecords"]:
        chosen.add(round((row["startJulianDateTDB"] - start) / 4))
    rows = []
    global_index = 0
    for metadata, first, batch_count, ranges in q.batches(q.layout(reader)):
        indices = sorted(i - global_index for i in chosen if global_index <= i < global_index + batch_count)
        if indices:
            moon_data, earth_data = (reader.read(*r) for r in ranges)
            for index in indices:
                moon, earth = (struct.unpack_from("<41d", data, index * 41 * 8) for data in (moon_data, earth_data))
                source = [[moon[2 + axis * 13 + k] - earth[2 + axis * 13 + k] for k in range(13)] for axis in range(3)]
                for x in (-1.0, -0.5, 0.0, 0.5, 1.0):
                    position, velocity = q.evaluate(source, x)
                    rows.append({"record": global_index + index, "x": x, "positionKm": position, "velocityKmPerTDBDay": velocity})
        global_index += batch_count
    result = {"sourceEvidenceSHA256": hashlib.sha256(MANIFEST.read_bytes()).hexdigest(),
              "selection": "257 uniformly spaced record indices, all candidate worst-bound records and all existing transition records; x=-1,-0.5,0,0.5,1 in every selected record",
              "recordCount": len(chosen), "rows": rows}
    path = ROOT / "Scripts/moon-data/de441-native-fixtures.json"
    path.write_bytes(q.direct.encoded(result))
    print(f"Wrote {len(rows)} direct-source state fixtures")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--binary", type=Path, default=ROOT / ".context/issue-184/compact/degree-5-shared-endpoints.bin")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--reference-fixtures", action="store_true", help="regenerate direct-source fixtures from the verified qualification cache")
    parser.add_argument("--cache", type=Path, default=ROOT / ".context/issue-184/compact")
    args = parser.parse_args()
    if args.reference_fixtures:
        reference_fixtures(args.cache)
        return
    manifest = json.loads(MANIFEST.read_bytes())
    candidate = next(c for c in manifest["candidates"] if c["name"] == "degree-5-shared-endpoints")
    if not candidate["passesRepresentationTarget"] or candidate["recordCount"] != manifest["coverage"]["recordCount"]:
        raise ValueError("candidate is not qualified for the complete source range")
    data = extract(OUTPUT.read_text()) if args.check else args.binary.read_bytes()
    validate(data, candidate)
    start = manifest["coverage"]["segments"][0]["firstRecordStartJulianDateTDB"] - 2451545
    source = render(data, start, candidate["recordCount"])
    if args.check:
        if OUTPUT.read_text() != source:
            raise SystemExit("Generated DE441 Moon table differs")
        print("Verified generated DE441 Moon table")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(source)
        print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
