#!/usr/bin/env python3
"""Generate the shipping UTC offset table offline from checksummed USNO records."""
import argparse
from decimal import Decimal
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'Scripts/accuracy/time-data'
OUTPUT = ROOT / 'Sources/AstronomyKit/UTCOffsetTable.swift'


def generate():
    manifest = json.loads((DATA/'manifest.json').read_text())
    for name, record in manifest['files'].items():
        if hashlib.sha256((DATA/name).read_bytes()).hexdigest() != record['sha256']:
            raise ValueError('Time source checksum mismatch')
    lines = (DATA/'tai-utc.dat').read_text().splitlines()
    entries = []
    previous = None
    for line in lines:
        match = re.search(r'=JD\s+([\d.]+)\s+TAI-UTC=\s+([\d.]+)\s+S\s+\+\s+\(MJD -\s*([\d.]+)\)\s+X\s+([\d.]+)', line)
        if not match:
            raise ValueError(f'Invalid USNO time segment: {line}')
        jd, tai, reference, rate = map(Decimal, match.groups())
        if previous is not None and jd <= previous:
            raise ValueError('Unordered time table')
        previous = jd
        start = jd - Decimal('2451545')
        offset = Decimal('32.184') + tai + (jd-Decimal('2400000.5')-reference)*rate
        entries.append(f'        Segment(start: {start}, offset: {offset}, rate: {rate}),')
    if len(entries) != 41:
        raise ValueError('Expected all 41 pinned USNO segments')
    return '''// Generated by Scripts/generate-time-table.py; do not edit.
// USNO TAI-UTC table, retrieved 2026-09-06; IERS Bulletin C 72.
// Source URLs and SHA-256: Scripts/accuracy/time-data/manifest.json.

extension CivilTime {
    static let segments: [Segment] = [
'''+ '\n'.join(entries) + '\n    ]\n}\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit('Generated UTC table differs')
    else:
        OUTPUT.write_text(expected)
    print('Verified UTC table' if args.check else 'Generated UTC table')
