#!/usr/bin/env python3
"""Generate the Swift series of Jupiter's moons offline from the checksummed C tables."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import struct

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'Scripts/jupiter-moon-data/manifest.json'
ENGINE = 'Sources/CLibAstronomy/astronomy.c'
OUTPUT = ROOT / 'Sources/AstronomyKit/Engine/Bodies/Generated/JupiterMoonSeries.swift'
MOONS = ['Io', 'Europa', 'Ganymede', 'Callisto']
ELEMENTS = ['a', 'l', 'z', 'zeta']
J2000 = 2451545.0
# L1.2's time origin and its angles Psi and I, as BisL1.2.dat prints them. The C engine holds the rotation they give,
# not the angles, so they are transcribed here; --published compares them with the file.
PUBLISHED_EPOCH = '0.2433282500D+07'
PUBLISHED_PSI = '0.6249501830657150D+01'
PUBLISHED_INCLINATION = '0.4450947364976650D+00'

HEADER = '''// Generated by Scripts/generate-jupiter-moon-series.py; do not edit.
// The leading terms of each series of the L1.2 theory (Lainey, Duriez and Vienne 2006), as Astronomy Engine keeps them,
// and the theory's time origin and rotation angles.
// Source path and SHA-256: Scripts/jupiter-moon-data/manifest.json.
// swift-format-ignore-file
'''


def model_block(source):
    """The C engine's Jupiter moon terms and model, from the first term array to the end of JupiterMoonModel."""
    match = re.search(r'static const vsop_term_t jm_Io_a\[\] =.*?static const jupiter_moon_t JupiterMoonModel\[\] =\n\{.*?\n\};', source, re.S)
    if not match:
        raise ValueError(f'{ENGINE} has no Jupiter moon model')
    return match.group(0)


def read_block(manifest):
    record = manifest['model']
    if record['path'] != ENGINE:
        raise ValueError(f'The Jupiter moon model must come from {ENGINE}')
    block = model_block((ROOT/ENGINE).read_text())
    if hashlib.sha256(block.encode('ascii')).hexdigest() != record['sha256']:
        raise ValueError(f'Jupiter moon model checksum mismatch in {ENGINE}')
    return block


def parse_model(block):
    """Per moon: mu, the mean longitude's phase and rate, and the (amplitude, phase, frequency) terms of a, L, z, zeta."""
    number = r'(-?\d+\.\d+(?:e[+-]\d+)?)'
    arrays = {}
    for match in re.finditer(r'static const vsop_term_t (jm_\w+)\[\] =\n\{(.*?)\n\};', block, re.S):
        terms = re.findall(r'\{\s*' + r',\s*'.join([number] * 3) + r'\s*\}', match.group(2))
        if len(terms) != match.group(2).count('{'):
            raise ValueError(f'Unparsed term in {match.group(1)}')
        arrays[match.group(1)] = [tuple(float(value) for value in term) for term in terms]
    table = re.search(r'JupiterMoonModel\[\] =\n\{(.*)\n\};', block, re.S).group(1)
    entry = (r'\{\s*' + number + r',\s*\{\s*' + number + r',\s*' + number + r'\s*\}'
             + ''.join(r'\s*,\s*\{\s*(\d+),\s*(jm_\w+)\s*\}' for _ in ELEMENTS) + r'\s*\}')
    models = []
    for moon, match in zip(MOONS, re.finditer(entry, table), strict=True):
        mu, phase, rate = (float(value) for value in match.groups()[:3])
        series = {}
        for index, element in enumerate(ELEMENTS):
            count, name = int(match.group(4 + 2 * index)), match.group(5 + 2 * index)
            if name != f'jm_{moon}_{element}' or len(arrays[name]) != count:
                raise ValueError(f'{moon} {element} does not name its own {count} terms')
            series[element] = arrays[name]
        models.append({'moon': moon, 'mu': mu, 'meanLongitude': (phase, rate), 'series': series})
    if len(models) != len(MOONS):
        raise ValueError('JupiterMoonModel must hold four moons')
    return models


def real(field):
    """A Fortran D-exponent number."""
    return float(field.replace('D', 'e'))


def generate(models):
    lines = [HEADER, 'extension Engine.JupiterMoons {',
             "    /// The series' time origin, 1950-01-01 00:00 TT (JD 2433282.5), in TT days from J2000.",
             f'    static let epochTT = {real(PUBLISHED_EPOCH) - J2000!r}',
             '',
             '    /// The angles Psi and I in radians that L1.2 publishes to rotate its jovicentric frame to the mean',
             '    /// equator and equinox of J2000.',
             f'    static let psi = {real(PUBLISHED_PSI)!r}',
             f'    static let inclination = {real(PUBLISHED_INCLINATION)!r}',
             '',
             '    /// The model of each moon, in the order of ``Moon``.',
             '    static let models: [Model] = [']
    for model in models:
        phase, rate = model['meanLongitude']
        lines.append(f'        // {model["moon"]}')
        lines.append('        Model(')
        lines.append(f'            mu: {model["mu"]!r},')
        lines.append(f'            meanLongitude: (phase: {phase!r}, rate: {rate!r}),')
        for index, element in enumerate(ELEMENTS):
            terms = model['series'][element]
            separator = ',' if index < len(ELEMENTS) - 1 else ''
            lines.append(f'            {element}: [')
            lines.extend(f'                Term({a!r}, {p!r}, {f!r}),' for a, p, f in terms)
            lines.append(f'            ]{separator}')
        lines.append('        ),')
    lines.extend(['    ]', '}', ''])
    return '\n'.join(lines)


def published_series(text):
    """BisL1.2.dat as L1.2.f's INITbis reads it: T0, the masses, Psi and I, and each moon's series and mean longitude."""
    lines = text.splitlines()
    position = 0
    t0 = real(lines[position][:18])
    position += 1 + 17
    masses = [real(lines[position][25 * k:25 * (k + 1)]) for k in range(4)]
    position += 1
    psi, inclination = real(lines[position][0:25]), real(lines[position][25:50])
    position += 1
    moons = []
    for _ in MOONS:
        series, longitude = {}, None
        for element in ELEMENTS:
            count = int(lines[position][:3])
            position += 1
            if element == 'l':
                longitude = (real(lines[position][0:25]), real(lines[position][25:50]))
                position += 1
            series[element] = [(float(line[3:23]), real(line[23:45]), real(line[45:67]))
                               for line in lines[position:position + count]]
            position += count
        moons.append({'meanLongitude': longitude, 'series': series})
    return {'t0': t0, 'masses': masses, 'psi': psi, 'inclination': inclination, 'moons': moons}


def bits(value):
    return struct.pack('<d', value)


def check_published(directory, manifest, models):
    """Every term against BisL1.2.dat as IMCCE publishes it, and the transcribed time origin, Psi and I."""
    for name, record in manifest['published']['files'].items():
        if hashlib.sha256((directory/name).read_bytes()).hexdigest() != record['sha256']:
            raise ValueError(f'Published file checksum mismatch: {name}')
    published = published_series((directory/'BisL1.2.dat').read_text(encoding='latin-1'))
    compared = 0
    for model, mass, moon in zip(models, published['masses'], published['moons'], strict=True):
        if bits(model['mu']) != bits(mass):
            raise ValueError(f'{model["moon"]} mu differs from BisL1.2.dat')
        if any(bits(x) != bits(y) for x, y in zip(model['meanLongitude'], moon['meanLongitude'], strict=True)):
            raise ValueError(f'{model["moon"]} mean longitude differs from BisL1.2.dat')
        for element in ELEMENTS:
            kept, full = model['series'][element], moon['series'][element]
            if [tuple(map(bits, term)) for term in kept] != [tuple(map(bits, term)) for term in full[:len(kept)]]:
                raise ValueError(f'{model["moon"]} {element} terms are not the leading terms of BisL1.2.dat')
            compared += len(kept)
    for name, transcribed in [('t0', PUBLISHED_EPOCH), ('psi', PUBLISHED_PSI), ('inclination', PUBLISHED_INCLINATION)]:
        if bits(real(transcribed)) != bits(published[name]):
            raise ValueError(f'{name} differs from BisL1.2.dat')
    return compared


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--published', type=Path, metavar='DIR',
                        help='also compare the series and constants with BisL1.2.dat in DIR (see the manifest)')
    args = parser.parse_args()
    manifest = json.loads(MANIFEST.read_text())
    models = parse_model(read_block(manifest))
    if args.published:
        compared = check_published(args.published, manifest, models)
        print(f'All {compared} terms are the leading terms of BisL1.2.dat; mu, the mean longitudes, '
              'Psi, I and T0 equal it')
    expected = generate(models)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit('Generated Jupiter moon series differ')
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(expected)
    print('Verified Jupiter moon series' if args.check else 'Generated Jupiter moon series')
