#!/usr/bin/env python3
"""Generate the Swift DE440 Moon table and the TDB series offline from the checksummed C sources."""
import argparse
import base64
import hashlib
import json
from pathlib import Path
import re
import struct

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'Scripts/moon-data/manifest.json'
MOON = 'Sources/CLibAstronomy/EphemerisData/moon_data.inc'
DTDB = 'Sources/CLibAstronomy/EphemerisTime/dtdb.c'
OUTPUT = ROOT / 'Sources/AstronomyKit/Engine/Moon/Generated'
J2000 = 2451545.0
AU_KM = 149597870.7
LINE = 128

HEADER = '''// Generated by Scripts/generate-moon-tables.py; do not edit.
// {content}.
// Source path and SHA-256: Scripts/moon-data/manifest.json.
// swift-format-ignore-file
'''


def read_sources(manifest):
    if set(manifest['files']) != {MOON, DTDB}:
        raise ValueError('Moon manifest must list exactly the DE440 Moon table and dtdb.c')
    sources = {}
    for name, record in manifest['files'].items():
        data = (ROOT/name).read_bytes()
        if hashlib.sha256(data).hexdigest() != record['sha256']:
            raise ValueError(f'Moon source checksum mismatch: {name}')
        sources[name] = data.decode('ascii')
    return sources


def moon_table(source):
    """The table's first TDB in days from J2000, its record length in days, its shape and its coefficients."""
    def define(name, pattern):
        return re.search(r'#define MOON_BUNDLE_' + name + r' ' + pattern, source).group(1)

    start = float.fromhex(define('START_TDB', r'\((0x[0-9a-fp.+-]+)\)')) - J2000
    end = float.fromhex(define('END_TDB', r'\((0x[0-9a-fp.+-]+)\)')) - J2000
    step = float.fromhex(define('STEP_DAYS', r'\((0x[0-9a-fp.+-]+)\)'))
    records = int(define('RECORD_COUNT', r'(\d+)'))
    count = int(define('COEFFICIENT_COUNT', r'(\d+)'))
    body = source.split('static const double moon_bundle_coefficients[] = {', 1)[1].split('};', 1)[0]
    items = [item.strip() for item in body.split(',') if item.strip()]
    values = [float.fromhex(item) for item in items]
    if len(values) != records * 3 * count:
        raise ValueError(f'The Moon table holds {len(values)} coefficients, not {records} x 3 x {count}')
    if not start + records * step >= end > start:
        raise ValueError('The Moon table does not reach its stated end')
    return start, step, records, count, values


def packed(values):
    """Base64 of the little-endian IEEE 754 bit patterns, as Swift multi-line string lines."""
    text = base64.b64encode(struct.pack(f'<{len(values)}d', *values)).decode('ascii')
    return '\n'.join(text[i:i + LINE] for i in range(0, len(text), LINE))


def moon_swift(source, content):
    start, step, records, count, values = moon_table(source)
    return HEADER.format(content=content) + f'''
extension Engine.MoonEphemeris {{
    /// The start of the first record, in TDB days from J2000.
    static let start: Double = {start!r}
    /// The length of each record in TDB days.
    static let recordDays: Double = {step!r}
    static let recordCount = {records:_}
    /// Chebyshev coefficients per axis in each record.
    static let degreeCount = {count}
    /// Record by record, then x, y and z, then by ascending degree; AU, ICRS axes.
    static let coefficients = Engine.unpackDoubles(
        count: {len(values):_},
        """
{packed(values)}
"""
    )
}}
'''


def tdb_terms(source):
    """Fairhead and Bretagnon's terms, grouped by the power of t that multiplies them."""
    table = source.split('static const double fairhd[787][3] = {', 1)[1].split('};', 1)[0]
    number = r'\s*(-?\d+\.\d+(?:e-?\d+)?)\s*'
    rows = re.findall(r'\{' + number + ',' + number + ',' + number + r'\}', table)
    if len(rows) != 787 or len(rows) != table.count('{'):
        raise ValueError('Expected all 787 terms of fairhd')
    loops = [(int(high), int(low)) for high, low in re.findall(r'for \(j = (\d+); j >= (\d+); j--\)', source)]
    if len(loops) != 5 or loops[0][1] != 0 or loops[-1][0] != 786 or any(
            loops[k][1] != loops[k - 1][0] + 1 for k in range(1, 5)):
        raise ValueError('Expected five loops over consecutive ranges of fairhd')
    return [rows[low:high + 1] for high, low in loops]


def tdb_swift(source, content):
    groups = []
    for power, rows in enumerate(tdb_terms(source)):
        lines = '\n'.join(f'            Term({amplitude}, {frequency}, {phase}),' for amplitude, frequency, phase in rows)
        groups.append(f'        // t^{power}: {len(rows)} terms.\n        [\n{lines}\n        ],')
    return HEADER.format(content=content) + '''
extension Engine.TDB {
    /// The terms of each power of t from 0 to 4, in ERFA's order: amplitude
    /// in seconds, frequency in radians per Julian millennium, phase in radians.
    static let terms: [[Term]] = [
''' + '\n'.join(groups) + '''
    ]
}
'''


def generate(manifest, sources):
    contents = {name: record['content'] for name, record in manifest['files'].items()}
    return {
        'MoonDE440Coefficients.swift': moon_swift(sources[MOON], contents[MOON]),
        'TDBTerms.swift': tdb_swift(sources[DTDB], contents[DTDB]),
    }


def spk_segments(data):
    """The (center, target) summaries of a little-endian DAF/SPK file."""
    if data[:8] != b'DAF/SPK ' or data[88:96] != b'LTL-IEEE':
        raise ValueError('Not a little-endian DAF/SPK file')
    nd, ni = struct.unpack('<ii', data[8:16])
    if (nd, ni) != (2, 6):
        raise ValueError('Unexpected SPK summary format')
    size = nd + (ni + 1) // 2
    segments, record = {}, struct.unpack('<i', data[76:80])[0]
    while record:
        base = (record - 1) * 1024
        following, _, count = struct.unpack('<3d', data[base:base + 24])
        for index in range(int(count)):
            offset = base + 24 + index * size * 8
            target, center, frame, kind, first, last = struct.unpack('<6i', data[offset + 16:offset + 40])
            segments[(center, target)] = (frame, kind, first, last)
        record = int(following)
    return segments


def type2_records(data, segment):
    """The first epoch (JD TDB), record length (days), record size and words of a type 2 segment."""
    frame, kind, first, last = segment
    if (frame, kind) != (1, 2):
        raise ValueError('Expected a type 2 segment on J2000 (ICRF) axes')
    epoch, length, size, count = struct.unpack('<4d', data[(last - 4) * 8:last * 8])
    words = struct.unpack(f'<{int(size * count)}d', data[(first - 1) * 8:(first - 1 + int(size * count)) * 8])
    return J2000 + epoch / 86400, length / 86400, int(size), int(count), words


def check_published(directory, manifest, source):
    """Every coefficient against Moon minus Earth from DE440, both relative to the Earth-Moon barycenter."""
    record = manifest['published']['files']['de440s.bsp']
    data = (directory/'de440s.bsp').read_bytes()
    if hashlib.sha256(data).hexdigest() != record['sha256']:
        raise ValueError('Published DE440 checksum mismatch: de440s.bsp')
    segments = spk_segments(data)
    moon = type2_records(data, segments[(3, 301)])
    earth = type2_records(data, segments[(3, 399)])
    if moon[:4] != earth[:4]:
        raise ValueError('The DE440 Moon and Earth segments have different records')
    epoch, length, size, count = moon[:4]
    start, step, records, degrees, values = moon_table(source)
    first = (J2000 + start - epoch) / length
    if step != length or size != 2 + 3 * degrees or first != int(first) or int(first) + records > count:
        raise ValueError('The Moon table does not fall on the DE440 records')
    for k in range(records):
        base = (int(first) + k) * size + 2
        for index in range(3 * degrees):
            expected = (moon[4][base + index] - earth[4][base + index]) / AU_KM
            if struct.pack('<d', values[k * 3 * degrees + index]) != struct.pack('<d', expected):
                raise ValueError(f'Record {k}, coefficient {index} differs from DE440')
    return records * 3 * degrees, int(first)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--published', type=Path, metavar='DIR',
                        help='also compare the Moon table with de440s.bsp in DIR (see the manifest)')
    args = parser.parse_args()
    manifest = json.loads(MANIFEST.read_text())
    sources = read_sources(manifest)
    if args.published:
        compared, first = check_published(args.published, manifest, sources[MOON])
        print(f'All {compared:,} Moon coefficients equal DE440 (Moon - Earth) / au from record {first:,}')
    expected = generate(manifest, sources)
    if args.check:
        present = {path.name for path in OUTPUT.glob('*.swift')}
        if present != set(expected) or any((OUTPUT/name).read_text() != text for name, text in expected.items()):
            raise SystemExit('Generated Moon tables differ')
    else:
        OUTPUT.mkdir(parents=True, exist_ok=True)
        for path in OUTPUT.glob('*.swift'):
            if path.name not in expected:
                path.unlink()
        for name, text in expected.items():
            (OUTPUT/name).write_text(text)
    print('Verified Moon tables' if args.check else 'Generated Moon tables')
