#!/usr/bin/env python3
"""Embed pinned Saturn center coefficients; own only Planets/Generated/Saturn."""
import argparse
import base64
import importlib.util
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
OUTPUT=ROOT/'Sources/AstronomyKit/Engine/Planets/Generated/Saturn'
MANIFEST=ROOT/'Scripts/saturn-data/assessment.json'
BODIES={6:'barycenter',10:'sun',699:'offset'}
spec=importlib.util.spec_from_file_location('packed_generator',ROOT/'Scripts/generate-moon-de441.py')
common=importlib.util.module_from_spec(spec);spec.loader.exec_module(common)


def render(data,name,body):
    encoded=base64.b64encode(data).decode('ascii')
    payload='\n'.join(encoded[i:i+128] for i in range(0,len(encoded),128))
    return f'''// Generated by Scripts/generate-saturn-tables.py; do not edit.
// Source and SHA-256: Scripts/saturn-data/assessment.json.
// swift-format-ignore-file

extension Engine.SaturnEphemeris {{
    static let {name} = Table(
        start: {body['startJDTDB']-2451545!r}, days: {body['recordDays']!r},
        recordCount: {body['recordCount']}, coefficientCount: {body['coefficientCount']},
        scalarBytes: {4 if body['encoding']=='float32' else 8},
        data: Engine.unpackBytes(count: {len(data)},
            """
{payload}
"""
        )
    )
}}
'''


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    parser.add_argument('--binaries',type=Path,default=ROOT/'.context/issue-92/saturn-assessment')
    args=parser.parse_args()
    candidate=json.loads(MANIFEST.read_bytes())['candidates']['float32']
    for target,name in BODIES.items():
        body=candidate['bodies'][str(target)]
        path=OUTPUT/f'Saturn{name.title()}Data.swift'
        data=common.extract(path.read_text()) if args.check else (args.binaries/f'float32-{target}.bin').read_bytes()
        common.validate(data,body)
        if len(data)!=body['recordCount']*3*body['coefficientCount']*(4 if body['encoding']=='float32' else 8):
            raise ValueError('Saturn coefficient layout differs')
        expected=render(data,name,body)
        if args.check:
            if path.read_text()!=expected: raise SystemExit('generated Saturn table differs')
        else:
            OUTPUT.mkdir(parents=True,exist_ok=True);path.write_text(expected)
    print('Verified Saturn tables' if args.check else 'Wrote Saturn tables')

if __name__=='__main__': main()
