#!/usr/bin/env python3
"""Generate complete model tables from pinned, checksum-verified upstream data.

No network or third-party Python packages are required. Consumers use the
committed headers; --check verifies regeneration leaves them unchanged.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "Scripts/model-data"
OUTPUT = ROOT / "Sources/CLibAstronomy/generated"
BODIES = dict(zip(("mer", "ven", "ear", "mar", "jup", "sat", "ura", "nep"),
                  ("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")))


def generate():
    manifest = json.loads((DATA / "manifest.json").read_text())
    for name, record in manifest["files"].items():
        if hashlib.sha256((DATA / name).read_bytes()).hexdigest() != record["sha256"]:
            raise ValueError(f"Source checksum mismatch: {name}")
    notice = ("/* Generated by Scripts/generate-models.py; do not edit.\n"
              f" * Astronomy Engine source revision {manifest['upstreamRevision']}.\n"
              " * See Scripts/model-data/manifest.json and THIRD_PARTY_NOTICES. */\n")
    output = [notice]
    for suffix, body in BODIES.items():
        lines = iter((DATA / f"VSOP87B.{suffix}").read_text().splitlines())
        counts = {1: [], 2: [], 3: []}
        for header in lines:
            match = re.search(r"VARIABLE\s+(\d).*\*T\*\*(\d)\s+(\d+) TERMS", header)
            if not match:
                raise ValueError(f"Invalid VSOP header: {header}")
            coordinate, power, count = map(int, match.groups())
            if power != len(counts[coordinate]) or count <= 0:
                raise ValueError("Missing or reordered VSOP series")
            counts[coordinate].append(count)
            name = f"vsop_{('lon', 'lat', 'rad')[coordinate-1]}_{body}_{power}"
            output.append(f"static const vsop_term_t {name}[] = {{\n")
            for index in range(count):
                row = next(lines)
                if int(row[5:10]) != index + 1:
                    raise ValueError("Missing or reordered VSOP term")
                # Preserve the full decimal source coefficients, without float formatting.
                terms = row.split()[-3:]
                if len(terms) != 3:
                    raise ValueError("Invalid VSOP coefficient row")
                output.append("    { " + ", ".join(terms) + " },\n")
            output.append("};\n")
        for coordinate, sizes in counts.items():
            name = f"vsop_{('lon', 'lat', 'rad')[coordinate-1]}_{body}"
            output.append(f"static const vsop_series_t {name}[] = {{\n")
            output.extend(f"    {{ {count}, {name}_{power} }},\n" for power, count in enumerate(sizes))
            output.append("};\n")
    nutation = [notice, "static const struct { int n[5]; double c[6]; } iau2000b_terms[] = {\n"]
    rows = (DATA / "iau2000b.txt").read_text().splitlines()
    if len(rows) != 77:
        raise ValueError("IAU2000B must contain exactly 77 terms")
    for row in rows:
        values = row.split()
        if len(values) != 11:
            raise ValueError("Invalid nutation coefficient row")
        nutation.append("    { { " + ", ".join(values[:5]) + " }, { " + ", ".join(values[5:]) + " } },\n")
    nutation.append("};\n")
    return {"vsop87b_full.h": "".join(output), "iau2000b_full.h": "".join(nutation)}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, content in generate().items():
        path = OUTPUT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"Generated model differs: {path}")
        else:
            path.write_text(content)
        print(f"Verified {name}" if args.check else f"Generated {name}")
