#!/usr/bin/env python3
"""Generate the Swift VSOP87B and polynomial planet tables offline from the checksummed C tables."""
import argparse
import base64
import hashlib
import json
import math
from pathlib import Path
import re
import struct

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'Scripts/planet-data/manifest.json'
VSOP = 'Sources/CLibAstronomy/generated/vsop87b_full.h'
POLYNOMIAL = 'Sources/CLibAstronomy/generated/polynomial-data.h'
OUTPUT = ROOT / 'Sources/AstronomyKit/Engine/Planets/Generated'
BODIES = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
COORDINATES = ['lon', 'lat', 'rad']
LINE = 128

HEADER = '''// Generated by Scripts/generate-planet-tables.py; do not edit.
// {content}.
// Source path and SHA-256: Scripts/planet-data/manifest.json.
// swift-format-ignore-file
'''


def packed(values):
    """Base64 of the little-endian IEEE 754 bit patterns, as Swift multi-line string lines."""
    text = base64.b64encode(struct.pack(f'<{len(values)}d', *values)).decode('ascii')
    return '\n'.join(text[i:i + LINE] for i in range(0, len(text), LINE))


def unpack_call(values):
    """The Swift expression that decodes `values` from their packed literal."""
    return f'''Engine.unpackDoubles(
            count: {len(values):_},
            """
{packed(values)}
"""
        )'''


def rows(values, indent, brackets=False):
    """One line per row of integers; each row in brackets when the Swift value is nested."""
    lines = (', '.join(f'{value:_}' for value in row) for row in values)
    return '\n'.join(f'{indent}[{line}],' if brackets else f'{indent}{line},' for line in lines)


def read_sources(manifest):
    if set(manifest['files']) != {VSOP, POLYNOMIAL}:
        raise ValueError('Planet manifest must list exactly the VSOP87B and polynomial tables')
    sources = {}
    for name, record in manifest['files'].items():
        data = (ROOT/name).read_bytes()
        if hashlib.sha256(data).hexdigest() != record['sha256']:
            raise ValueError(f'Planet source checksum mismatch: {name}')
        sources[name] = data.decode('ascii')
    return sources


def vsop_tables(source):
    """Each body's term counts per coordinate and power, and its terms in evaluation order."""
    term = r'\{\s*(-?\d+\.\d+),\s*(-?\d+\.\d+),\s*(-?\d+\.\d+)\s*\}'
    arrays = {}
    for match in re.finditer(r'static const vsop_term_t (vsop_\w+)\[\] = \{(.*?)\n\};', source, re.S):
        triples = re.findall(term, match.group(2))
        if len(triples) != match.group(2).count('{'):
            raise ValueError(f'Unparsed VSOP87B term in {match.group(1)}')
        arrays[match.group(1)] = [tuple(float(value) for value in triple) for triple in triples]
    used = set()
    tables = []
    for body in BODIES:
        layout, values = [], []
        for coordinate in COORDINATES:
            name = f'vsop_{coordinate}_{body}'
            match = re.search(r'static const vsop_series_t ' + name + r'\[\] = \{(.*?)\n\};', source, re.S)
            series = re.findall(r'\{\s*(\d+),\s*(vsop_\w+)\s*\}', match.group(1))
            if len(series) != match.group(1).count('{'):
                raise ValueError(f'Unparsed VSOP87B series in {name}')
            row = []
            for power, (count, array) in enumerate(series):
                if array != f'{name}_{power}' or int(count) != len(arrays[array]):
                    raise ValueError(f'VSOP87B series {name} power {power} does not match its terms')
                used.add(array)
                row.append(int(count))
                values.extend(value for triple in arrays[array] for value in triple)
            layout.append(row)
        tables.append((body, layout, values))
    if used != set(arrays):
        raise ValueError('VSOP87B term arrays not reached from any series')
    return tables


def published_tables(directory, manifest):
    """The same layout and terms read from the VSOP87B files IMCCE publishes."""
    tables = []
    for body in BODIES:
        name = f'VSOP87B.{body[:3].lower()}'
        data = (directory/name).read_bytes()
        if hashlib.sha256(data).hexdigest() != manifest['published']['files'][name]['sha256']:
            raise ValueError(f'Published VSOP87B checksum mismatch: {name}')
        layout, values, expected = [[], [], []], [], 0
        for line in data.decode('ascii').splitlines():
            header = re.search(r'VARIABLE (\d) \(LBR\)\s+\*T\*\*(\d)\s+(\d+) TERMS', line)
            if header:
                if expected:
                    raise ValueError(f'{name}: series ended early')
                coordinate, power, expected = (int(group) for group in header.groups())
                if power != len(layout[coordinate - 1]):
                    raise ValueError(f'{name}: powers out of order')
                layout[coordinate - 1].append(expected)
            else:
                # Each term line ends with the amplitude A, the phase B and the frequency C.
                values.extend(float(field) for field in line.split()[-3:])
                expected -= 1
        if expected:
            raise ValueError(f'{name}: series ended early')
        tables.append((body, layout, values))
    return tables


def vsop_swift(source, content):
    models = []
    for body, layout, values in vsop_tables(source):
        models.append(f'''    static let {body.lower()} = Model(
        termCounts: [
{rows(layout, '            ', brackets=True)}
        ],
        terms: {unpack_call(values)}
    )''')
    return HEADER.format(content=content) + f'''
extension Engine.VSOP87B {{
{chr(10).join(models)}
}}
'''


def c_array(source, kind, name):
    """The comma-separated items of the C array `name`."""
    text = re.search(r'static const ' + kind + r' ' + name + r'\[\] = \{(.*?)\};', source, re.S).group(1)
    return [item for item in text.replace('\n', '').split(',') if item]


def polynomial_tables(source):
    def constant(name):
        return float.fromhex(re.search(r'#define ' + name + r' \((-?0x[0-9a-fp.+-]+)\)', source).group(1))

    start, stop = constant('POLYNOMIAL_START'), constant('POLYNOMIAL_STOP')
    models = re.findall(r'\{(\d+),(\d+),polynomial_(\w+),polynomial_valid_(\w+)\}', source)
    if [model[2] for model in models] != BODIES or [model[3] for model in models] != BODIES:
        raise ValueError('Polynomial models are not Mercury to Neptune in order')
    tables = []
    for degree, width, body, _ in models:
        degree, width = int(degree), float(width)
        coefficients = [float.fromhex(item) for item in c_array(source, 'double', f'polynomial_{body}')]
        valid = [int(item) for item in c_array(source, 'unsigned char', f'polynomial_valid_{body}')]
        segments = math.ceil((stop - start) / width)
        if len(valid) != segments or set(valid) - {0, 1} or len(coefficients) != segments * 3 * (degree + 1):
            raise ValueError(f'Polynomial table for {body} does not cover {segments} segments')
        excluded = [index for index, flag in enumerate(valid) if not flag]
        tables.append((body, degree, width, excluded, coefficients))
    return start, stop, tables


def polynomial_swift(body, degree, width, excluded, coefficients, content):
    excluded_text = '[]' if not excluded else '[\n' + rows(
        [excluded[i:i + 12] for i in range(0, len(excluded), 12)], '            ') + '\n        ]'
    return HEADER.format(content=content) + f'''
extension Engine.PlanetPolynomial {{
    static let {body.lower()} = Model(
        degree: {degree},
        width: {width:g},
        excludedSegments: {excluded_text},
        coefficients: {unpack_call(coefficients)}
    )
}}
'''


def coverage_swift(start, stop, content):
    return HEADER.format(content=content) + f'''
extension Engine.PlanetPolynomial {{
    /// The first TT, in days from J2000, that the tables cover: 1900-01-01 00:00 TT.
    static let start: Double = {start.hex()}
    /// The first TT after the tables: 2101-01-01 00:00 TT.
    static let stop: Double = {stop.hex()}
}}
'''


def generate(manifest, sources):
    contents = {name: record['content'] for name, record in manifest['files'].items()}
    files = {'VSOP87BTerms.swift': vsop_swift(sources[VSOP], contents[VSOP])}
    start, stop, tables = polynomial_tables(sources[POLYNOMIAL])
    content = contents[POLYNOMIAL]
    files['PlanetPolynomialCoverage.swift'] = coverage_swift(start, stop, content)
    for body, degree, width, excluded, coefficients in tables:
        files[f'PlanetPolynomial{body}.swift'] = polynomial_swift(body, degree, width, excluded, coefficients, content)
    return files


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--published', type=Path, metavar='DIR',
                        help='also compare the C table with the IMCCE VSOP87B files in DIR (see the manifest)')
    args = parser.parse_args()
    manifest = json.loads(MANIFEST.read_text())
    sources = read_sources(manifest)
    if args.published:
        if vsop_tables(sources[VSOP]) != published_tables(args.published, manifest):
            raise SystemExit('The VSOP87B table differs from the published files')
        print('The VSOP87B table matches the published files term for term')
    expected = generate(manifest, sources)
    if args.check:
        present = {path.name for path in OUTPUT.glob('*.swift')}
        if present != set(expected) or any((OUTPUT/name).read_text() != text for name, text in expected.items()):
            raise SystemExit('Generated planet tables differ')
    else:
        OUTPUT.mkdir(parents=True, exist_ok=True)
        for path in OUTPUT.glob('*.swift'):
            if path.name not in expected:
                path.unlink()
        for name, text in expected.items():
            (OUTPUT/name).write_text(text)
    print('Verified planet tables' if args.check else 'Generated planet tables')
